-- =============================================================================
-- hyprland/workspaces.lua
-- Workspace layout engine settings, gap configuration, and workspace rules.
--
-- NOTE: Per-monitor workspace assignment is handled by nwg-displays or manually
-- via `hyprctl keyword wsbind <ws> <monitor>`.  The file
-- ~/.config/hypr/monitors.conf (generated by nwg-displays) will be sourced by
-- the installer via a symlink if present.
-- =============================================================================

-- ---------------------------------------------------------------------------
-- Layout engine: dwindle
-- ---------------------------------------------------------------------------
hl.config({
    dwindle = {
        pseudotile         = true,   -- press SUPER+P to toggle pseudo-tile
        preserve_split     = true,   -- keep split direction when closing a window
        force_split        = 0,      -- 0 = follow mouse, 1 = always left, 2 = always right
        smart_split        = false,
        smart_resizing     = true,
        permanent_direction_override = false,
        special_scale_factor = 0.8,
        no_gaps_when_only  = false,
    },

    -- Master layout (alternative; activate via `hyprctl keyword general:layout master`)
    master = {
        new_is_master         = false,
        new_on_top            = false,
        no_gaps_when_only     = false,
        orientation           = "left",
        special_scale_factor  = 0.8,
        mfact                 = 0.5,
        allow_small_split     = false,
    },

    -- Active layout (use dwindle by default)
    general = {
        layout = "dwindle",
    },
})

-- ---------------------------------------------------------------------------
-- Gaps
-- ---------------------------------------------------------------------------
hl.config({
    general = {
        gaps_in  = 6,    -- gap between tiled windows
        gaps_out = 10,   -- gap between windows and screen edge
        gaps_workspaces = 0,
        border_size = 2,
        -- Border colours come from the theme engine.
        -- Defaults here are ARGB hex fallbacks.
        ["col.active_border"]   = "rgba(cba6f7ff) rgba(89b4faff) 45deg",
        ["col.inactive_border"] = "rgba(595959aa)",
        ["col.nogroup_border_active"]   = "rgba(cba6f7ff)",
        ["col.nogroup_border_inactive"] = "rgba(595959aa)",
        resize_on_border  = true,
        extend_border_grab_area = 15,
        hover_icon_on_border = true,
        no_focus_fallback = false,
    },
})

-- ---------------------------------------------------------------------------
-- Workspace rules
-- ---------------------------------------------------------------------------

-- Scratchpad (special:special) — smaller, centred
hl.config({
    ["workspace:special:special"] = "gapsin:30, gapsout:50",
})

-- Optionally pin workspace 1 to the primary monitor (eDP/HDMI).
-- Uncomment and adjust after running nwg-displays:
-- hl.config({ ["wsbind:1"] = "eDP-1" })

-- ---------------------------------------------------------------------------
-- Group rules (window groups / tabs)
-- ---------------------------------------------------------------------------
hl.config({
    group = {
        insert_after_current = true,
        focus_removed_window = true,
        ["col.border_active"]         = "rgba(cba6f7ff)",
        ["col.border_inactive"]       = "rgba(595959aa)",
        ["col.border_locked_active"]  = "rgba(f38ba8ff)",
        ["col.border_locked_inactive"] = "rgba(45475aaa)",
        groupbar = {
            enabled         = true,
            height          = 20,
            gradients       = true,
            render_titles   = true,
            scrolling       = true,
            font_size       = 11,
            ["col.active"]  = "rgba(cba6f7ff)",
            ["col.inactive"] = "rgba(595959aa)",
            ["col.locked_active"]  = "rgba(f38ba8ff)",
            ["col.locked_inactive"] = "rgba(45475aaa)",
        },
    },
})
